train_set:
  module: torchvision.datasets.oxford_iiit_pet
  name: OxfordIIITPet
  params:
    root: data
    split: trainval
    download: true
    # target_types: ['category']  # default is 'category'
    transform:
      resize:
        type: Resize
        params:
          size: [256, 256]
      center_crop:
        type: CenterCrop
        params:
          size: [224, 224]
      to_tensor:
        type: ToTensor
      normalize:
        type: Normalize
        params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  batch_size: 64
  shuffle: True
  num_workers: 4
  pin_memory: True
  persistent_workers: True

projection_set:
  module: torchvision.datasets.oxford_iiit_pet
  name: OxfordIIITPet
  params:
    root: data
    split: trainval
    download: true
    # target_types: ['category']  # default is 'category'
    transform:
      resize:
        type: Resize
        params:
          size: [256, 256]
      center_crop:
        type: CenterCrop
        params:
          size: [224, 224]
      to_tensor:
        type: ToTensor
      normalize:
        type: Normalize
        params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  batch_size: 64
  shuffle: True
  num_workers: 4
  pin_memory: True
  persistent_workers: True

test_set:
  module: torchvision.datasets.oxford_iiit_pet
  name: OxfordIIITPet
  params:
    root: data
    split: test
    download: true
    # target_types: ['category']  # default is 'category'
    transform:
      resize:
        type: Resize
        params:
          size: [256, 256]
      center_crop:
        type: CenterCrop
        params:
          size: [224, 224]
      to_tensor:
        type: ToTensor
      normalize:
        type: Normalize
        params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  batch_size: 64
  shuffle: True
  num_workers: 4
  pin_memory: True
  persistent_workers: True

