top_arch:
  module: cabrnet.archs.protopnet.model
  name: ProtoPNet

extractor:
  backbone:
    arch: wide_resnet50_2
    layer: layer4
    # arch: efficientnet_b0
    # layer: features
    weights: IMAGENET1K_V1
  add_on:
    init_mode: XAVIER
    conv1:
      type: Conv2d
      params:
        out_channels: 128
        kernel_size: 1
        bias: False
    sigmoid1:
      type: Sigmoid

similarity:
  name: ProtoPNetSimilarity

classifier:
  module: cabrnet.archs.protopnet.decision
  name: ProtoPNetClassifier
  params:
    num_classes: 100
    num_proto_per_class: 10
    proto_init_mode: SHIFTED_NORMAL
