site_name: CaBRNet documentation
repo_url: https://github.com/aiser-team/cabrnet/
repo_name: GitLab
docs_dir: manuals
use_directory_urls: false
site_dir: ../website
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - .js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js